name: portal

services:
  db:
    image: postgres:17
    restart: always
    env_file:
      - backend/.env
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: portal-postgres-data
