// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserGroup = `-- name: AddUserGroup :exec
INSERT INTO user_groups (user_id, "group")
VALUES ($1, $2)
ON CONFLICT (user_id, "group") DO NOTHING
`

type AddUserGroupParams struct {
	UserID pgtype.UUID
	Group  GroupType
}

func (q *Queries) AddUserGroup(ctx context.Context, arg AddUserGroupParams) error {
	_, err := q.db.Exec(ctx, addUserGroup, arg.UserID, arg.Group)
	return err
}

const countAdminAuditLogs = `-- name: CountAdminAuditLogs :one
SELECT COUNT(*)
FROM admin_audit_logs aal
JOIN users actor
    ON actor.id = aal.actor_user_id
WHERE (
    $1::text IS NULL
    OR actor.full_name ILIKE '%' || $1::text || '%'
)
`

func (q *Queries) CountAdminAuditLogs(ctx context.Context, actorName pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminAuditLogs, actorName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersAdmin = `-- name: CountUsersAdmin :one
WITH args AS (
    SELECT
        $1::text AS full_name,
        $2::text AS student_id,
        $3::text AS email,
        $4::role_type AS role,
        $5::boolean AS is_student,
        $6::text[] AS groups,
        $7::text[] AS membership_tier_ids
)
SELECT COUNT(*)
FROM users u
CROSS JOIN args a
WHERE (
    a.full_name IS NULL
    OR u.full_name ILIKE '%' || a.full_name || '%'
)
AND (
    a.student_id IS NULL
    OR u.student_id ILIKE '%' || a.student_id || '%'
)
AND (
    a.email IS NULL
    OR u.email ILIKE '%' || a.email || '%'
)
AND (
    a.role IS NULL
    OR u.role = a.role
)
AND (
    a.is_student IS NULL
    OR u.is_student = a.is_student
)
AND (
    a.groups IS NULL
    OR ARRAY(
        SELECT filter_group."group"::text
        FROM user_groups filter_group
        WHERE filter_group.user_id = u.id
        ORDER BY filter_group."group"::text
    ) = a.groups
)
AND (
    a.membership_tier_ids IS NULL
    OR ARRAY(
        SELECT DISTINCT filter_tier.tier_id::text
        FROM memberships filter_tier
        WHERE filter_tier.user_id = u.id
          AND filter_tier.cancelled_at IS NULL
          AND filter_tier.started_at <= NOW()
          AND filter_tier.expires_at > NOW()
        ORDER BY filter_tier.tier_id::text
    ) = a.membership_tier_ids
)
`

type CountUsersAdminParams struct {
	FullName          pgtype.Text
	StudentID         pgtype.Text
	Email             pgtype.Text
	Role              NullRoleType
	IsStudent         pgtype.Bool
	Groups            []string
	MembershipTierIds []string
}

func (q *Queries) CountUsersAdmin(ctx context.Context, arg CountUsersAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersAdmin,
		arg.FullName,
		arg.StudentID,
		arg.Email,
		arg.Role,
		arg.IsStudent,
		arg.Groups,
		arg.MembershipTierIds,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminAuditLog = `-- name: CreateAdminAuditLog :exec
INSERT INTO admin_audit_logs (
    actor_user_id,
    action,
    target_user_id,
    outcome,
    request_id,
    description
) VALUES (
    $1::uuid,
    $2::text,
    $3::uuid,
    $4::admin_audit_outcome_type,
    $5::text,
    $6::text
)
`

type CreateAdminAuditLogParams struct {
	ActorUserID  pgtype.UUID
	Action       string
	TargetUserID pgtype.UUID
	Outcome      AdminAuditOutcomeType
	RequestID    string
	Description  pgtype.Text
}

func (q *Queries) CreateAdminAuditLog(ctx context.Context, arg CreateAdminAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAdminAuditLog,
		arg.ActorUserID,
		arg.Action,
		arg.TargetUserID,
		arg.Outcome,
		arg.RequestID,
		arg.Description,
	)
	return err
}

const createExecProfile = `-- name: CreateExecProfile :exec
INSERT INTO exec_profile (
    user_id, 
    title,
    display_order,
    display_group
) VALUES (
    $1::uuid,
    $2::text,
    $3::int,
    $4::exec_display_group_type
)
`

type CreateExecProfileParams struct {
	UserID       pgtype.UUID
	Title        pgtype.Text
	DisplayOrder pgtype.Int4
	DisplayGroup NullExecDisplayGroupType
}

func (q *Queries) CreateExecProfile(ctx context.Context, arg CreateExecProfileParams) error {
	_, err := q.db.Exec(ctx, createExecProfile,
		arg.UserID,
		arg.Title,
		arg.DisplayOrder,
		arg.DisplayGroup,
	)
	return err
}

const getAdminAuditLogs = `-- name: GetAdminAuditLogs :many
WITH args AS (
    SELECT
        $1::text AS actor_name,
        $2::integer AS "limit",
        $3::integer AS "offset"
)
SELECT
    aal.id,
    aal.occurred_at,
    aal.action,
    aal.outcome,
    aal.request_id,
    aal.description,
    actor.id AS actor_id,
    actor.full_name AS actor_name,
    actor.avatar_url AS actor_avatar_url,
    target.id AS target_id,
    target.full_name AS target_name,
    target.avatar_url AS target_avatar_url
FROM admin_audit_logs aal
JOIN users actor
    ON actor.id = aal.actor_user_id
LEFT JOIN users target
    ON target.id = aal.target_user_id
CROSS JOIN args a
WHERE (
    a.actor_name IS NULL
    OR actor.full_name ILIKE '%' || a.actor_name || '%'
)
ORDER BY
    aal.occurred_at DESC,
    aal.id DESC
LIMIT (SELECT "limit" FROM args)
OFFSET (SELECT "offset" FROM args)
`

type GetAdminAuditLogsParams struct {
	ActorName pgtype.Text
	Limit     int32
	Offset    int32
}

type GetAdminAuditLogsRow struct {
	ID              pgtype.UUID
	OccurredAt      pgtype.Timestamptz
	Action          string
	Outcome         AdminAuditOutcomeType
	RequestID       string
	Description     pgtype.Text
	ActorID         pgtype.UUID
	ActorName       string
	ActorAvatarUrl  pgtype.Text
	TargetID        pgtype.UUID
	TargetName      pgtype.Text
	TargetAvatarUrl pgtype.Text
}

func (q *Queries) GetAdminAuditLogs(ctx context.Context, arg GetAdminAuditLogsParams) ([]GetAdminAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, getAdminAuditLogs, arg.ActorName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdminAuditLogsRow
	for rows.Next() {
		var i GetAdminAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Action,
			&i.Outcome,
			&i.RequestID,
			&i.Description,
			&i.ActorID,
			&i.ActorName,
			&i.ActorAvatarUrl,
			&i.TargetID,
			&i.TargetName,
			&i.TargetAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminMembershipTierOptions = `-- name: GetAdminMembershipTierOptions :many
SELECT
    mt.id,
    mt.title,
    mp.program_name
FROM membership_tiers mt
JOIN membership_programs mp ON mp.id = mt.program_id
ORDER BY mp.program_name, mt.title, mt.id
`

type GetAdminMembershipTierOptionsRow struct {
	ID          pgtype.UUID
	Title       string
	ProgramName string
}

func (q *Queries) GetAdminMembershipTierOptions(ctx context.Context) ([]GetAdminMembershipTierOptionsRow, error) {
	rows, err := q.db.Query(ctx, getAdminMembershipTierOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdminMembershipTierOptionsRow
	for rows.Next() {
		var i GetAdminMembershipTierOptionsRow
		if err := rows.Scan(&i.ID, &i.Title, &i.ProgramName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminUserByID = `-- name: GetAdminUserByID :one
SELECT
    u.id,
    u.email,
    u.student_id,
    u.role,
    u.created_at,
    u.updated_at,
    u.full_name,
    u.email_verified_at,
    u.is_student,
    u.onboarding_completed_at,
    u.avatar_url,
    COALESCE(g.groups, '{}'::text[])::text[] AS groups
FROM users u
LEFT JOIN LATERAL (
    SELECT array_agg(
        ug."group"::text
        ORDER BY ug.assigned_at, ug."group"
    ) AS groups
    FROM user_groups ug
    WHERE ug.user_id = u.id
) g ON true
WHERE u.id = $1
`

type GetAdminUserByIDRow struct {
	ID                    pgtype.UUID
	Email                 string
	StudentID             pgtype.Text
	Role                  RoleType
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	FullName              string
	EmailVerifiedAt       pgtype.Timestamptz
	IsStudent             bool
	OnboardingCompletedAt pgtype.Timestamptz
	AvatarUrl             pgtype.Text
	Groups                []string
}

func (q *Queries) GetAdminUserByID(ctx context.Context, id pgtype.UUID) (GetAdminUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminUserByID, id)
	var i GetAdminUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.StudentID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FullName,
		&i.EmailVerifiedAt,
		&i.IsStudent,
		&i.OnboardingCompletedAt,
		&i.AvatarUrl,
		&i.Groups,
	)
	return i, err
}

const getExecProfileByUserID = `-- name: GetExecProfileByUserID :one
SELECT
    user_id,
    title,
    display_order,
    display_group
FROM exec_profile
WHERE user_id = $1
`

type GetExecProfileByUserIDRow struct {
	UserID       pgtype.UUID
	Title        string
	DisplayOrder int32
	DisplayGroup ExecDisplayGroupType
}

func (q *Queries) GetExecProfileByUserID(ctx context.Context, userID pgtype.UUID) (GetExecProfileByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getExecProfileByUserID, userID)
	var i GetExecProfileByUserIDRow
	err := row.Scan(
		&i.UserID,
		&i.Title,
		&i.DisplayOrder,
		&i.DisplayGroup,
	)
	return i, err
}

const getUsersAdmin = `-- name: GetUsersAdmin :many
WITH args AS (
    SELECT
        $1::text AS full_name,
        $2::text AS student_id,
        $3::text AS email,
        $4::role_type AS role,
        $5::boolean AS is_student,
        $6::text[] AS groups,
        $7::text[] AS membership_tier_ids,
        $8::integer AS "limit",
        $9::integer AS "offset"
)
SELECT
    u.id,
    u.email,
    u.student_id,
    u.role,
    u.created_at,
    u.updated_at,
    u.full_name,
    u.email_verified_at,
    u.is_student,
    u.onboarding_completed_at,
    u.avatar_url,
    COALESCE(g.groups, '{}'::text[])::text[] AS groups,
    COALESCE(am.tier_titles, '{}'::text[])::text[] AS active_membership_tier_titles
FROM users u
CROSS JOIN args a
LEFT JOIN LATERAL (
    SELECT array_agg(
        ug."group"::text
        ORDER BY ug.assigned_at, ug."group"
    ) AS groups
    FROM user_groups ug
    WHERE ug.user_id = u.id
) g ON true
LEFT JOIN LATERAL (
    SELECT
        array_agg(mt.title ORDER BY mt.title, mt.id) AS tier_titles
    FROM memberships m
    JOIN membership_tiers mt ON mt.id = m.tier_id
    WHERE m.user_id = u.id
      AND m.cancelled_at IS NULL
      AND m.started_at <= NOW()
      AND m.expires_at > NOW()
) am ON true
WHERE (
    a.full_name IS NULL
    OR u.full_name ILIKE '%' || a.full_name || '%'
)
AND (
    a.student_id IS NULL
    OR u.student_id ILIKE '%' || a.student_id || '%'
)
AND (
    a.email IS NULL
    OR u.email ILIKE '%' || a.email || '%'
)
AND (
    a.role IS NULL
    OR u.role = a.role
)
AND (
    a.is_student IS NULL
    OR u.is_student = a.is_student
)
AND (
    a.groups IS NULL
    OR ARRAY(
        SELECT filter_group."group"::text
        FROM user_groups filter_group
        WHERE filter_group.user_id = u.id
        ORDER BY filter_group."group"::text
    ) = a.groups
)
AND (
    a.membership_tier_ids IS NULL
    OR ARRAY(
        SELECT DISTINCT filter_tier.tier_id::text
        FROM memberships filter_tier
        WHERE filter_tier.user_id = u.id
          AND filter_tier.cancelled_at IS NULL
          AND filter_tier.started_at <= NOW()
          AND filter_tier.expires_at > NOW()
        ORDER BY filter_tier.tier_id::text
    ) = a.membership_tier_ids
)
ORDER BY u.created_at DESC
LIMIT (SELECT "limit" FROM args)
OFFSET (SELECT "offset" FROM args)
`

type GetUsersAdminParams struct {
	FullName          pgtype.Text
	StudentID         pgtype.Text
	Email             pgtype.Text
	Role              NullRoleType
	IsStudent         pgtype.Bool
	Groups            []string
	MembershipTierIds []string
	Limit             pgtype.Int4
	Offset            pgtype.Int4
}

type GetUsersAdminRow struct {
	ID                         pgtype.UUID
	Email                      string
	StudentID                  pgtype.Text
	Role                       RoleType
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	FullName                   string
	EmailVerifiedAt            pgtype.Timestamptz
	IsStudent                  bool
	OnboardingCompletedAt      pgtype.Timestamptz
	AvatarUrl                  pgtype.Text
	Groups                     []string
	ActiveMembershipTierTitles []string
}

func (q *Queries) GetUsersAdmin(ctx context.Context, arg GetUsersAdminParams) ([]GetUsersAdminRow, error) {
	rows, err := q.db.Query(ctx, getUsersAdmin,
		arg.FullName,
		arg.StudentID,
		arg.Email,
		arg.Role,
		arg.IsStudent,
		arg.Groups,
		arg.MembershipTierIds,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersAdminRow
	for rows.Next() {
		var i GetUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.StudentID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FullName,
			&i.EmailVerifiedAt,
			&i.IsStudent,
			&i.OnboardingCompletedAt,
			&i.AvatarUrl,
			&i.Groups,
			&i.ActiveMembershipTierTitles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasActiveMembershipForUser = `-- name: HasActiveMembershipForUser :one
SELECT EXISTS (
    SELECT 1
    FROM memberships
    WHERE user_id = $1
      AND cancelled_at IS NULL
)
`

func (q *Queries) HasActiveMembershipForUser(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveMembershipForUser, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasExecGroupForUser = `-- name: HasExecGroupForUser :one
SELECT EXISTS (
    SELECT 1 
    FROM user_groups
    WHERE user_id = $1
        AND "group" IN ('executive', 'director', 'board')
)
`

func (q *Queries) HasExecGroupForUser(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasExecGroupForUser, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasExecProfileForUser = `-- name: HasExecProfileForUser :one
SELECT EXISTS (
    SELECT 1 
    FROM exec_profile
    WHERE user_id = $1
)
`

func (q *Queries) HasExecProfileForUser(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasExecProfileForUser, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeExecProfile = `-- name: RemoveExecProfile :exec
DELETE FROM exec_profile
WHERE user_id = $1
`

func (q *Queries) RemoveExecProfile(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeExecProfile, userID)
	return err
}

const removeUserGroup = `-- name: RemoveUserGroup :exec
DELETE FROM user_groups
WHERE user_id = $1 AND "group" = $2
`

type RemoveUserGroupParams struct {
	UserID pgtype.UUID
	Group  GroupType
}

func (q *Queries) RemoveUserGroup(ctx context.Context, arg RemoveUserGroupParams) error {
	_, err := q.db.Exec(ctx, removeUserGroup, arg.UserID, arg.Group)
	return err
}

const studentIDExists = `-- name: StudentIDExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE student_id = $1
)
`

func (q *Queries) StudentIDExists(ctx context.Context, studentID pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, studentIDExists, studentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateExecProfile = `-- name: UpdateExecProfile :exec
UPDATE exec_profile
SET
    title = COALESCE($1, title),
    display_order = COALESCE($2, display_order),
    display_group = COALESCE($3, display_group),
    updated_at = NOW()
WHERE user_id = $4
`

type UpdateExecProfileParams struct {
	Title        pgtype.Text
	DisplayOrder pgtype.Int4
	DisplayGroup NullExecDisplayGroupType
	UserID       pgtype.UUID
}

func (q *Queries) UpdateExecProfile(ctx context.Context, arg UpdateExecProfileParams) error {
	_, err := q.db.Exec(ctx, updateExecProfile,
		arg.Title,
		arg.DisplayOrder,
		arg.DisplayGroup,
		arg.UserID,
	)
	return err
}

const updateUserFullName = `-- name: UpdateUserFullName :exec
UPDATE users
SET full_name = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateUserFullNameParams struct {
	FullName string
	ID       pgtype.UUID
}

func (q *Queries) UpdateUserFullName(ctx context.Context, arg UpdateUserFullNameParams) error {
	_, err := q.db.Exec(ctx, updateUserFullName, arg.FullName, arg.ID)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users
SET
    role = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID   pgtype.UUID
	Role RoleType
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}

const updateUserStudentInfo = `-- name: UpdateUserStudentInfo :exec
UPDATE users
SET
    is_student = $2,
    student_id = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserStudentInfoParams struct {
	ID        pgtype.UUID
	IsStudent bool
	StudentID pgtype.Text
}

func (q *Queries) UpdateUserStudentInfo(ctx context.Context, arg UpdateUserStudentInfoParams) error {
	_, err := q.db.Exec(ctx, updateUserStudentInfo, arg.ID, arg.IsStudent, arg.StudentID)
	return err
}
