// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveMembershipsCount = `-- name: GetActiveMembershipsCount :one
WITH args AS (
    SELECT
        $1::text AS program_name,
        $2::text[] AS tier_ids,
        $3::boolean AS is_student
)
SELECT COUNT(*)
FROM memberships m
JOIN membership_tiers mt ON mt.id = m.tier_id
JOIN membership_programs mp ON mp.id = mt.program_id
JOIN users u ON u.id = m.user_id
CROSS JOIN args a
WHERE m.cancelled_at IS NULL
  AND m.started_at <= NOW()
  AND m.expires_at > NOW()
  AND (a.program_name IS NULL OR mp.program_name = a.program_name)
  AND (a.tier_ids IS NULL OR mt.id::text = ANY(a.tier_ids))
  AND (a.is_student IS NULL OR u.is_student = a.is_student)
`

type GetActiveMembershipsCountParams struct {
	ProgramName pgtype.Text
	TierIds     []string
	IsStudent   pgtype.Bool
}

func (q *Queries) GetActiveMembershipsCount(ctx context.Context, arg GetActiveMembershipsCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getActiveMembershipsCount, arg.ProgramName, arg.TierIds, arg.IsStudent)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllTimeRevenueCents = `-- name: GetAllTimeRevenueCents :one
WITH args AS (
    SELECT
        $1::text AS program_name,
        $2::text[] AS tier_ids,
        $3::boolean AS is_student,
        $4::purchase_type AS purchase_type
)
SELECT COALESCE(SUM(t.amount_paid_cents), 0)::bigint AS revenue_cents
FROM transactions t
JOIN membership_tiers mt ON mt.id = t.tier_id
JOIN membership_programs mp ON mp.id = mt.program_id
CROSS JOIN args a
WHERE t.status = 'completed'
  AND (a.program_name IS NULL OR mp.program_name = a.program_name)
  AND (a.tier_ids IS NULL OR mt.id::text = ANY(a.tier_ids))
  AND (a.is_student IS NULL OR t.student_at_purchase = a.is_student)
  AND (a.purchase_type IS NULL OR t.purchase_type = a.purchase_type)
`

type GetAllTimeRevenueCentsParams struct {
	ProgramName  pgtype.Text
	TierIds      []string
	IsStudent    pgtype.Bool
	PurchaseType NullPurchaseType
}

func (q *Queries) GetAllTimeRevenueCents(ctx context.Context, arg GetAllTimeRevenueCentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, getAllTimeRevenueCents,
		arg.ProgramName,
		arg.TierIds,
		arg.IsStudent,
		arg.PurchaseType,
	)
	var revenue_cents int64
	err := row.Scan(&revenue_cents)
	return revenue_cents, err
}

const getMembershipsBoughtOverTime = `-- name: GetMembershipsBoughtOverTime :many
WITH args AS (
    SELECT
        $1::text AS granularity,
        $2::timestamptz AS from_date,
        $3::timestamptz AS to_date,
        $4::text AS program_name,
        $5::text[] AS tier_ids,
        $6::boolean AS is_student
)
SELECT
    date_trunc((SELECT granularity FROM args), t.created_at, 'UTC')::timestamptz AS bucket,
    COUNT(*) AS count
FROM transactions t
JOIN membership_tiers mt ON mt.id = t.tier_id
JOIN membership_programs mp ON mp.id = mt.program_id
CROSS JOIN args a
WHERE t.status = 'completed'
  AND (a.from_date IS NULL OR t.created_at >= a.from_date)
  AND t.created_at < a.to_date
  AND (a.program_name IS NULL OR mp.program_name = a.program_name)
  AND (a.tier_ids IS NULL OR mt.id::text = ANY(a.tier_ids))
  AND (a.is_student IS NULL OR t.student_at_purchase = a.is_student)
GROUP BY bucket
ORDER BY bucket
`

type GetMembershipsBoughtOverTimeParams struct {
	Granularity string
	FromDate    pgtype.Timestamptz
	ToDate      pgtype.Timestamptz
	ProgramName pgtype.Text
	TierIds     []string
	IsStudent   pgtype.Bool
}

type GetMembershipsBoughtOverTimeRow struct {
	Bucket pgtype.Timestamptz
	Count  int64
}

func (q *Queries) GetMembershipsBoughtOverTime(ctx context.Context, arg GetMembershipsBoughtOverTimeParams) ([]GetMembershipsBoughtOverTimeRow, error) {
	rows, err := q.db.Query(ctx, getMembershipsBoughtOverTime,
		arg.Granularity,
		arg.FromDate,
		arg.ToDate,
		arg.ProgramName,
		arg.TierIds,
		arg.IsStudent,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMembershipsBoughtOverTimeRow
	for rows.Next() {
		var i GetMembershipsBoughtOverTimeRow
		if err := rows.Scan(&i.Bucket, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRevenueOverTime = `-- name: GetRevenueOverTime :many
WITH args AS (
    SELECT
        $1::text AS granularity,
        $2::timestamptz AS from_date,
        $3::timestamptz AS to_date,
        $4::text AS program_name,
        $5::text[] AS tier_ids,
        $6::boolean AS is_student,
        $7::purchase_type AS purchase_type
)
SELECT
    date_trunc((SELECT granularity FROM args), t.created_at, 'UTC')::timestamptz AS bucket,
    COALESCE(SUM(t.amount_paid_cents), 0)::bigint AS revenue_cents
FROM transactions t
JOIN membership_tiers mt ON mt.id = t.tier_id
JOIN membership_programs mp ON mp.id = mt.program_id
CROSS JOIN args a
WHERE t.status = 'completed'
  AND (a.from_date IS NULL OR t.created_at >= a.from_date)
  AND t.created_at < a.to_date
  AND (a.program_name IS NULL OR mp.program_name = a.program_name)
  AND (a.tier_ids IS NULL OR mt.id::text = ANY(a.tier_ids))
  AND (a.is_student IS NULL OR t.student_at_purchase = a.is_student)
  AND (a.purchase_type IS NULL OR t.purchase_type = a.purchase_type)
GROUP BY bucket
ORDER BY bucket
`

type GetRevenueOverTimeParams struct {
	Granularity  string
	FromDate     pgtype.Timestamptz
	ToDate       pgtype.Timestamptz
	ProgramName  pgtype.Text
	TierIds      []string
	IsStudent    pgtype.Bool
	PurchaseType NullPurchaseType
}

type GetRevenueOverTimeRow struct {
	Bucket       pgtype.Timestamptz
	RevenueCents int64
}

func (q *Queries) GetRevenueOverTime(ctx context.Context, arg GetRevenueOverTimeParams) ([]GetRevenueOverTimeRow, error) {
	rows, err := q.db.Query(ctx, getRevenueOverTime,
		arg.Granularity,
		arg.FromDate,
		arg.ToDate,
		arg.ProgramName,
		arg.TierIds,
		arg.IsStudent,
		arg.PurchaseType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRevenueOverTimeRow
	for rows.Next() {
		var i GetRevenueOverTimeRow
		if err := rows.Scan(&i.Bucket, &i.RevenueCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUniqueMembersCount = `-- name: GetUniqueMembersCount :one
WITH args AS (
    SELECT
        $1::text AS program_name,
        $2::text[] AS tier_ids,
        $3::boolean AS is_student,
        $4::purchase_type AS purchase_type
)
SELECT COUNT(DISTINCT t.user_id)
FROM transactions t
JOIN membership_tiers mt ON mt.id = t.tier_id
JOIN membership_programs mp ON mp.id = mt.program_id
CROSS JOIN args a
WHERE t.status = 'completed'
  AND (a.program_name IS NULL OR mp.program_name = a.program_name)
  AND (a.tier_ids IS NULL OR mt.id::text = ANY(a.tier_ids))
  AND (a.is_student IS NULL OR t.student_at_purchase = a.is_student)
  AND (a.purchase_type IS NULL OR t.purchase_type = a.purchase_type)
`

type GetUniqueMembersCountParams struct {
	ProgramName  pgtype.Text
	TierIds      []string
	IsStudent    pgtype.Bool
	PurchaseType NullPurchaseType
}

func (q *Queries) GetUniqueMembersCount(ctx context.Context, arg GetUniqueMembersCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getUniqueMembersCount,
		arg.ProgramName,
		arg.TierIds,
		arg.IsStudent,
		arg.PurchaseType,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}
