// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exec_profile.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExecSocialLink = `-- name: DeleteExecSocialLink :exec

DELETE FROM exec_social_link 
WHERE user_id = $1 AND platform = $2
`

type DeleteExecSocialLinkParams struct {
	UserID   pgtype.UUID
	Platform ExecSocialPlatformType
}

// UPDATE exec_social_link
// SET url = $3, updated_at = NOW()
// WHERE user_id = $1 AND platform = $2;
func (q *Queries) DeleteExecSocialLink(ctx context.Context, arg DeleteExecSocialLinkParams) error {
	_, err := q.db.Exec(ctx, deleteExecSocialLink, arg.UserID, arg.Platform)
	return err
}

const getExecProfiles = `-- name: GetExecProfiles :many
SELECT 
    e.user_id,
    e.title,
    e.display_order,
    e.display_group,
    u.full_name,
    u.avatar_url,
    COALESCE(
        json_agg(
            json_build_object(
                'platform', s.platform,
                'url', s.url
            )
        ) FILTER (WHERE s.platform IS NOT NULL),
        '[]'::json
    ) AS social_links
FROM exec_profile e
JOIN users u ON e.user_id = u.id
LEFT JOIN exec_social_link s ON e.user_id = s.user_id
GROUP BY e.user_id, e.title, e.display_order, e.display_group, u.full_name, u.avatar_url
ORDER BY e.display_order ASC, u.full_name ASC, e.user_id ASC
`

type GetExecProfilesRow struct {
	UserID       pgtype.UUID
	Title        string
	DisplayOrder int32
	DisplayGroup ExecDisplayGroupType
	FullName     string
	AvatarUrl    pgtype.Text
	SocialLinks  interface{}
}

func (q *Queries) GetExecProfiles(ctx context.Context) ([]GetExecProfilesRow, error) {
	rows, err := q.db.Query(ctx, getExecProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExecProfilesRow
	for rows.Next() {
		var i GetExecProfilesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Title,
			&i.DisplayOrder,
			&i.DisplayGroup,
			&i.FullName,
			&i.AvatarUrl,
			&i.SocialLinks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExecProfileTitle = `-- name: UpdateExecProfileTitle :exec
UPDATE exec_profile
SET title = $2, updated_at = NOW()
WHERE user_id = $1
`

type UpdateExecProfileTitleParams struct {
	UserID pgtype.UUID
	Title  string
}

func (q *Queries) UpdateExecProfileTitle(ctx context.Context, arg UpdateExecProfileTitleParams) error {
	_, err := q.db.Exec(ctx, updateExecProfileTitle, arg.UserID, arg.Title)
	return err
}

const updateExecSocialLink = `-- name: UpdateExecSocialLink :exec
INSERT INTO exec_social_link (user_id, platform, url)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, platform)
DO UPDATE SET url = EXCLUDED.url, updated_at = NOW()
`

type UpdateExecSocialLinkParams struct {
	UserID   pgtype.UUID
	Platform ExecSocialPlatformType
	Url      string
}

func (q *Queries) UpdateExecSocialLink(ctx context.Context, arg UpdateExecSocialLinkParams) error {
	_, err := q.db.Exec(ctx, updateExecSocialLink, arg.UserID, arg.Platform, arg.Url)
	return err
}
