// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: membership_invitation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMembershipInvitation = `-- name: CreateMembershipInvitation :one
WITH inserted AS (
    INSERT INTO membership_invitations (
        email,
        tier_id,
        amount_paid_cents,
        payment_method,
        created_by_user_id,
        invitation_sent_at
    ) VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        NOW()
    )
    RETURNING id, email, tier_id, amount_paid_cents, payment_method, done, created_by_user_id, invitation_sent_at, purchased_at, created_at, updated_at
)
SELECT
    p.id,
    p.email,
    p.tier_id,
    mt.title AS tier_title,
    mp.program_name,
    p.amount_paid_cents,
    p.payment_method,
    p.done,
    p.created_by_user_id,
    creator.full_name AS created_by_name,
    p.invitation_sent_at,
    p.purchased_at,
    p.created_at,
    p.updated_at
FROM inserted p
JOIN membership_tiers mt ON mt.id = p.tier_id
JOIN membership_programs mp ON mp.id = mt.program_id
JOIN users creator ON creator.id = p.created_by_user_id
`

type CreateMembershipInvitationParams struct {
	Email           string
	TierID          pgtype.UUID
	AmountPaidCents int64
	PaymentMethod   PaymentMethodType
	CreatedByUserID pgtype.UUID
}

type CreateMembershipInvitationRow struct {
	ID               pgtype.UUID
	Email            string
	TierID           pgtype.UUID
	TierTitle        string
	ProgramName      string
	AmountPaidCents  int64
	PaymentMethod    PaymentMethodType
	Done             bool
	CreatedByUserID  pgtype.UUID
	CreatedByName    string
	InvitationSentAt pgtype.Timestamptz
	PurchasedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateMembershipInvitation(ctx context.Context, arg CreateMembershipInvitationParams) (CreateMembershipInvitationRow, error) {
	row := q.db.QueryRow(ctx, createMembershipInvitation,
		arg.Email,
		arg.TierID,
		arg.AmountPaidCents,
		arg.PaymentMethod,
		arg.CreatedByUserID,
	)
	var i CreateMembershipInvitationRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TierID,
		&i.TierTitle,
		&i.ProgramName,
		&i.AmountPaidCents,
		&i.PaymentMethod,
		&i.Done,
		&i.CreatedByUserID,
		&i.CreatedByName,
		&i.InvitationSentAt,
		&i.PurchasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMembershipInvitation = `-- name: DeleteMembershipInvitation :execrows
DELETE FROM membership_invitations
WHERE id = $1
`

func (q *Queries) DeleteMembershipInvitation(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMembershipInvitation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMembershipInvitationByEmailForUpdate = `-- name: GetMembershipInvitationByEmailForUpdate :one
SELECT
    p.id,
    p.tier_id,
    p.amount_paid_cents,
    p.payment_method,
    p.purchased_at,
    mt.program_id,
    mt.expiration_type
FROM membership_invitations p
JOIN membership_tiers mt ON mt.id = p.tier_id
WHERE LOWER(p.email) = LOWER($1)
  AND p.done = FALSE
FOR UPDATE OF p
`

type GetMembershipInvitationByEmailForUpdateRow struct {
	ID              pgtype.UUID
	TierID          pgtype.UUID
	AmountPaidCents int64
	PaymentMethod   PaymentMethodType
	PurchasedAt     pgtype.Timestamptz
	ProgramID       pgtype.UUID
	ExpirationType  MembershipExpirationType
}

func (q *Queries) GetMembershipInvitationByEmailForUpdate(ctx context.Context, email string) (GetMembershipInvitationByEmailForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getMembershipInvitationByEmailForUpdate, email)
	var i GetMembershipInvitationByEmailForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.TierID,
		&i.AmountPaidCents,
		&i.PaymentMethod,
		&i.PurchasedAt,
		&i.ProgramID,
		&i.ExpirationType,
	)
	return i, err
}

const getMembershipInvitationByID = `-- name: GetMembershipInvitationByID :one
SELECT
    p.id,
    p.email,
    p.tier_id,
    mt.title AS tier_title,
    mp.program_name,
    p.amount_paid_cents,
    p.payment_method,
    p.done,
    p.created_by_user_id,
    creator.full_name AS created_by_name,
    p.invitation_sent_at,
    p.purchased_at,
    p.created_at,
    p.updated_at
FROM membership_invitations p
JOIN membership_tiers mt ON mt.id = p.tier_id
JOIN membership_programs mp ON mp.id = mt.program_id
JOIN users creator ON creator.id = p.created_by_user_id
WHERE p.id = $1
`

type GetMembershipInvitationByIDRow struct {
	ID               pgtype.UUID
	Email            string
	TierID           pgtype.UUID
	TierTitle        string
	ProgramName      string
	AmountPaidCents  int64
	PaymentMethod    PaymentMethodType
	Done             bool
	CreatedByUserID  pgtype.UUID
	CreatedByName    string
	InvitationSentAt pgtype.Timestamptz
	PurchasedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetMembershipInvitationByID(ctx context.Context, id pgtype.UUID) (GetMembershipInvitationByIDRow, error) {
	row := q.db.QueryRow(ctx, getMembershipInvitationByID, id)
	var i GetMembershipInvitationByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TierID,
		&i.TierTitle,
		&i.ProgramName,
		&i.AmountPaidCents,
		&i.PaymentMethod,
		&i.Done,
		&i.CreatedByUserID,
		&i.CreatedByName,
		&i.InvitationSentAt,
		&i.PurchasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembershipInvitations = `-- name: GetMembershipInvitations :many
SELECT
    p.id,
    p.email,
    p.tier_id,
    mt.title AS tier_title,
    mp.program_name,
    p.amount_paid_cents,
    p.payment_method,
    p.done,
    p.created_by_user_id,
    creator.full_name AS created_by_name,
    p.invitation_sent_at,
    p.purchased_at,
    p.created_at,
    p.updated_at
FROM membership_invitations p
JOIN membership_tiers mt ON mt.id = p.tier_id
JOIN membership_programs mp ON mp.id = mt.program_id
JOIN users creator ON creator.id = p.created_by_user_id
ORDER BY p.created_at DESC, p.id DESC
`

type GetMembershipInvitationsRow struct {
	ID               pgtype.UUID
	Email            string
	TierID           pgtype.UUID
	TierTitle        string
	ProgramName      string
	AmountPaidCents  int64
	PaymentMethod    PaymentMethodType
	Done             bool
	CreatedByUserID  pgtype.UUID
	CreatedByName    string
	InvitationSentAt pgtype.Timestamptz
	PurchasedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetMembershipInvitations(ctx context.Context) ([]GetMembershipInvitationsRow, error) {
	rows, err := q.db.Query(ctx, getMembershipInvitations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMembershipInvitationsRow
	for rows.Next() {
		var i GetMembershipInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.TierID,
			&i.TierTitle,
			&i.ProgramName,
			&i.AmountPaidCents,
			&i.PaymentMethod,
			&i.Done,
			&i.CreatedByUserID,
			&i.CreatedByName,
			&i.InvitationSentAt,
			&i.PurchasedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMembershipInvitationDone = `-- name: MarkMembershipInvitationDone :execrows
UPDATE membership_invitations
SET
    done = TRUE,
    updated_at = NOW()
WHERE id = $1
  AND done = FALSE
`

func (q *Queries) MarkMembershipInvitationDone(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markMembershipInvitationDone, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const membershipInvitationUserExistsByEmail = `-- name: MembershipInvitationUserExistsByEmail :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE LOWER(email) = LOWER($1)
)
`

func (q *Queries) MembershipInvitationUserExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, membershipInvitationUserExistsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
