// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: membership.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelActiveMembershipByUserIdAndMembershipId = `-- name: CancelActiveMembershipByUserIdAndMembershipId :execrows
UPDATE memberships
SET
    cancelled_at = $3,
    updated_at = $3
WHERE user_id = $1
    AND id = $2
    AND cancelled_at IS NULL
    AND started_at <= NOW()
    AND expires_at > NOW()
`

type CancelActiveMembershipByUserIdAndMembershipIdParams struct {
	UserID      pgtype.UUID
	ID          pgtype.UUID
	CancelledAt pgtype.Timestamptz
}

func (q *Queries) CancelActiveMembershipByUserIdAndMembershipId(ctx context.Context, arg CancelActiveMembershipByUserIdAndMembershipIdParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelActiveMembershipByUserIdAndMembershipId, arg.UserID, arg.ID, arg.CancelledAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelActiveMembershipsByUserIdAndProgramId = `-- name: CancelActiveMembershipsByUserIdAndProgramId :exec
UPDATE memberships AS m
SET
    cancelled_at = $3,
    updated_at = $3
FROM membership_tiers AS mt
WHERE mt.id = m.tier_id
    AND m.user_id = $1
    AND mt.program_id = $2
    AND m.cancelled_at IS NULL
    AND m.started_at <= NOW()
    AND m.expires_at > NOW()
`

type CancelActiveMembershipsByUserIdAndProgramIdParams struct {
	UserID      pgtype.UUID
	ProgramID   pgtype.UUID
	CancelledAt pgtype.Timestamptz
}

func (q *Queries) CancelActiveMembershipsByUserIdAndProgramId(ctx context.Context, arg CancelActiveMembershipsByUserIdAndProgramIdParams) error {
	_, err := q.db.Exec(ctx, cancelActiveMembershipsByUserIdAndProgramId, arg.UserID, arg.ProgramID, arg.CancelledAt)
	return err
}

const completeTransaction = `-- name: CompleteTransaction :exec
UPDATE transactions
SET
    membership_id = $2,
    stripe_payment_intent_id = $3,
    amount_paid_cents = $4,
    status = 'completed',
    updated_at = NOW()
WHERE id = $1 AND status = 'pending'
`

type CompleteTransactionParams struct {
	ID                    pgtype.UUID
	MembershipID          pgtype.UUID
	StripePaymentIntentID pgtype.Text
	AmountPaidCents       pgtype.Int8
}

func (q *Queries) CompleteTransaction(ctx context.Context, arg CompleteTransactionParams) error {
	_, err := q.db.Exec(ctx, completeTransaction,
		arg.ID,
		arg.MembershipID,
		arg.StripePaymentIntentID,
		arg.AmountPaidCents,
	)
	return err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (
    user_id,
    tier_id,
    started_at,
    expires_at
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id
`

type CreateMembershipParams struct {
	UserID    pgtype.UUID
	TierID    pgtype.UUID
	StartedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.UserID,
		arg.TierID,
		arg.StartedAt,
		arg.ExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createPendingTransaction = `-- name: CreatePendingTransaction :one
INSERT INTO transactions (
    user_id,
    tier_id,
    group_at_purchase,
    student_at_purchase,
    purchase_type,
    payment_method,
    status
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    'pending'
)
RETURNING id
`

type CreatePendingTransactionParams struct {
	UserID            pgtype.UUID
	TierID            pgtype.UUID
	GroupAtPurchase   NullGroupType
	StudentAtPurchase pgtype.Bool
	PurchaseType      NullPurchaseType
	PaymentMethod     PaymentMethodType
}

func (q *Queries) CreatePendingTransaction(ctx context.Context, arg CreatePendingTransactionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createPendingTransaction,
		arg.UserID,
		arg.TierID,
		arg.GroupAtPurchase,
		arg.StudentAtPurchase,
		arg.PurchaseType,
		arg.PaymentMethod,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const expirePendingTransactionById = `-- name: ExpirePendingTransactionById :exec
UPDATE transactions
SET
    status = 'expired',
    updated_at = NOW()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) ExpirePendingTransactionById(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, expirePendingTransactionById, id)
	return err
}

const getActiveMembershipsExpiringOnDate = `-- name: GetActiveMembershipsExpiringOnDate :many
SELECT
    m.id,
    m.user_id,
    m.expires_at,
    mt.title AS tier_title,
    u.email
FROM memberships m
JOIN membership_tiers mt ON mt.id = m.tier_id
JOIN users u ON u.id = m.user_id
WHERE m.cancelled_at IS NULL
    AND (m.expires_at AT TIME ZONE 'America/Vancouver')::date = $1::date
`

type GetActiveMembershipsExpiringOnDateRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	TierTitle string
	Email     string
}

// Active (non-cancelled) memberships whose expires_at falls on the given
// calendar date in Vancouver time. Used by the daily expiry-notification job:
// called with (expiry date - 7 days) for "expiring soon" emails, and with
// today's date for "expired" emails.
func (q *Queries) GetActiveMembershipsExpiringOnDate(ctx context.Context, dollar_1 pgtype.Date) ([]GetActiveMembershipsExpiringOnDateRow, error) {
	rows, err := q.db.Query(ctx, getActiveMembershipsExpiringOnDate, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveMembershipsExpiringOnDateRow
	for rows.Next() {
		var i GetActiveMembershipsExpiringOnDateRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExpiresAt,
			&i.TierTitle,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveTiersWithPrices = `-- name: GetActiveTiersWithPrices :many
SELECT
    mt.id,
    mt.title,
    mt.description,
    mt.benefits,
    mt.limitations,
    mt.stripe_product_id,
    mt.slug,
    mt."group" AS required_group,
    mt.expiration_type,
    mtp.stripe_price_id,
    mtp.price_in_cents,
    mtp.is_student_required,
    mp.id AS program_id,
    mp.program_name
FROM membership_tiers mt
JOIN membership_tier_prices mtp
    ON mtp.tier_id = mt.id
JOIN membership_programs mp
    ON mp.id = mt.program_id
WHERE mt.is_active = TRUE
ORDER BY
    mp.program_name,
    mt.title
`

type GetActiveTiersWithPricesRow struct {
	ID                pgtype.UUID
	Title             string
	Description       pgtype.Text
	Benefits          []string
	Limitations       []string
	StripeProductID   pgtype.Text
	Slug              pgtype.Text
	RequiredGroup     NullGroupType
	ExpirationType    MembershipExpirationType
	StripePriceID     pgtype.Text
	PriceInCents      pgtype.Int8
	IsStudentRequired pgtype.Bool
	ProgramID         pgtype.UUID
	ProgramName       string
}

func (q *Queries) GetActiveTiersWithPrices(ctx context.Context) ([]GetActiveTiersWithPricesRow, error) {
	rows, err := q.db.Query(ctx, getActiveTiersWithPrices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveTiersWithPricesRow
	for rows.Next() {
		var i GetActiveTiersWithPricesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Benefits,
			&i.Limitations,
			&i.StripeProductID,
			&i.Slug,
			&i.RequiredGroup,
			&i.ExpirationType,
			&i.StripePriceID,
			&i.PriceInCents,
			&i.IsStudentRequired,
			&i.ProgramID,
			&i.ProgramName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMembershipsWithTransactions = `-- name: GetAllMembershipsWithTransactions :many
SELECT
    m.id,
    m.tier_id,
    mt.title AS tier_title,
    mt.slug,
    m.started_at,
    m.expires_at,
    m.cancelled_at,
    t.id AS transaction_id,
    t.amount_paid_cents,
    t.status,
    t.student_at_purchase,
    t.purchase_type,
    t.stripe_payment_intent_id,
    t.group_at_purchase,
    t.payment_method,
    mp.id AS program_id,
    mp.program_name
FROM memberships m
JOIN membership_tiers mt
    ON mt.id = m.tier_id
JOIN membership_programs mp
    ON mp.id = mt.program_id
JOIN transactions t
    ON t.membership_id = m.id
WHERE m.user_id = $1
ORDER BY m.started_at DESC
`

type GetAllMembershipsWithTransactionsRow struct {
	ID                    pgtype.UUID
	TierID                pgtype.UUID
	TierTitle             string
	Slug                  pgtype.Text
	StartedAt             pgtype.Timestamptz
	ExpiresAt             pgtype.Timestamptz
	CancelledAt           pgtype.Timestamptz
	TransactionID         pgtype.UUID
	AmountPaidCents       pgtype.Int8
	Status                TransactionStatusType
	StudentAtPurchase     pgtype.Bool
	PurchaseType          NullPurchaseType
	StripePaymentIntentID pgtype.Text
	GroupAtPurchase       NullGroupType
	PaymentMethod         PaymentMethodType
	ProgramID             pgtype.UUID
	ProgramName           string
}

func (q *Queries) GetAllMembershipsWithTransactions(ctx context.Context, userID pgtype.UUID) ([]GetAllMembershipsWithTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getAllMembershipsWithTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllMembershipsWithTransactionsRow
	for rows.Next() {
		var i GetAllMembershipsWithTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TierID,
			&i.TierTitle,
			&i.Slug,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.CancelledAt,
			&i.TransactionID,
			&i.AmountPaidCents,
			&i.Status,
			&i.StudentAtPurchase,
			&i.PurchaseType,
			&i.StripePaymentIntentID,
			&i.GroupAtPurchase,
			&i.PaymentMethod,
			&i.ProgramID,
			&i.ProgramName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentMembershipsWithTransactions = `-- name: GetCurrentMembershipsWithTransactions :many
SELECT
    m.id,
    m.tier_id,
    mt.title AS tier_title,
    mt.slug,
    m.started_at,
    m.expires_at,
    m.cancelled_at,
    t.id AS transaction_id,
    t.amount_paid_cents,
    t.status,
    t.purchase_type,
    t.student_at_purchase,
    t.stripe_payment_intent_id,
    t.group_at_purchase,
    t.payment_method,
    mp.id AS program_id,
    mp.program_name
FROM memberships m
JOIN membership_tiers mt
    ON mt.id = m.tier_id
JOIN membership_programs mp
    ON mp.id = mt.program_id
JOIN transactions t
    ON t.membership_id = m.id
WHERE m.user_id = $1
    AND m.cancelled_at IS NULL
    AND m.started_at <= NOW()
    AND m.expires_at > NOW()
ORDER BY m.started_at DESC
`

type GetCurrentMembershipsWithTransactionsRow struct {
	ID                    pgtype.UUID
	TierID                pgtype.UUID
	TierTitle             string
	Slug                  pgtype.Text
	StartedAt             pgtype.Timestamptz
	ExpiresAt             pgtype.Timestamptz
	CancelledAt           pgtype.Timestamptz
	TransactionID         pgtype.UUID
	AmountPaidCents       pgtype.Int8
	Status                TransactionStatusType
	PurchaseType          NullPurchaseType
	StudentAtPurchase     pgtype.Bool
	StripePaymentIntentID pgtype.Text
	GroupAtPurchase       NullGroupType
	PaymentMethod         PaymentMethodType
	ProgramID             pgtype.UUID
	ProgramName           string
}

func (q *Queries) GetCurrentMembershipsWithTransactions(ctx context.Context, userID pgtype.UUID) ([]GetCurrentMembershipsWithTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getCurrentMembershipsWithTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCurrentMembershipsWithTransactionsRow
	for rows.Next() {
		var i GetCurrentMembershipsWithTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TierID,
			&i.TierTitle,
			&i.Slug,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.CancelledAt,
			&i.TransactionID,
			&i.AmountPaidCents,
			&i.Status,
			&i.PurchaseType,
			&i.StudentAtPurchase,
			&i.StripePaymentIntentID,
			&i.GroupAtPurchase,
			&i.PaymentMethod,
			&i.ProgramID,
			&i.ProgramName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingTransactionForUpdate = `-- name: GetPendingTransactionForUpdate :one

SELECT
    id,
    stripe_checkout_session_id
FROM transactions
WHERE user_id = $1 AND status = 'pending'
FOR UPDATE
`

type GetPendingTransactionForUpdateRow struct {
	ID                      pgtype.UUID
	StripeCheckoutSessionID pgtype.Text
}

// Transaction related stuff
func (q *Queries) GetPendingTransactionForUpdate(ctx context.Context, userID pgtype.UUID) (GetPendingTransactionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getPendingTransactionForUpdate, userID)
	var i GetPendingTransactionForUpdateRow
	err := row.Scan(&i.ID, &i.StripeCheckoutSessionID)
	return i, err
}

const getPublicTiersAndPrices = `-- name: GetPublicTiersAndPrices :many
SELECT
    mt.id,
    mt.title,
    mt.description,
    mt.benefits,
    mt.limitations,
    mt.slug,
    mt.stripe_product_id,
    mt.expiration_type,
    mtp.stripe_price_id,
    mtp.price_in_cents,
    mtp.is_student_required,
    mp.id AS program_id,
    mp.program_name
FROM membership_tiers mt
JOIN membership_tier_prices mtp
    ON mtp.tier_id = mt.id
JOIN membership_programs mp
    ON mp.id = mt.program_id
WHERE mt.is_active = TRUE AND mt."group" = 'member'
`

type GetPublicTiersAndPricesRow struct {
	ID                pgtype.UUID
	Title             string
	Description       pgtype.Text
	Benefits          []string
	Limitations       []string
	Slug              pgtype.Text
	StripeProductID   pgtype.Text
	ExpirationType    MembershipExpirationType
	StripePriceID     pgtype.Text
	PriceInCents      pgtype.Int8
	IsStudentRequired pgtype.Bool
	ProgramID         pgtype.UUID
	ProgramName       string
}

func (q *Queries) GetPublicTiersAndPrices(ctx context.Context) ([]GetPublicTiersAndPricesRow, error) {
	rows, err := q.db.Query(ctx, getPublicTiersAndPrices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPublicTiersAndPricesRow
	for rows.Next() {
		var i GetPublicTiersAndPricesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Benefits,
			&i.Limitations,
			&i.Slug,
			&i.StripeProductID,
			&i.ExpirationType,
			&i.StripePriceID,
			&i.PriceInCents,
			&i.IsStudentRequired,
			&i.ProgramID,
			&i.ProgramName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTierByTierId = `-- name: GetTierByTierId :one
SELECT
    mt.id,
    mt.title,
    mt.description,
    mt.benefits,
    mt.limitations,
    mt.slug,
    mt.stripe_product_id,
    mt.expiration_type,
    mtp.stripe_price_id,
    mtp.price_in_cents,
    mtp.is_student_required,
    mp.id AS program_id,
    mp.program_name
FROM membership_tiers mt
JOIN membership_tier_prices mtp
    ON mtp.tier_id = mt.id
JOIN membership_programs mp
    ON mp.id = mt.program_id
WHERE mt.id = $1
`

type GetTierByTierIdRow struct {
	ID                pgtype.UUID
	Title             string
	Description       pgtype.Text
	Benefits          []string
	Limitations       []string
	Slug              pgtype.Text
	StripeProductID   pgtype.Text
	ExpirationType    MembershipExpirationType
	StripePriceID     pgtype.Text
	PriceInCents      pgtype.Int8
	IsStudentRequired pgtype.Bool
	ProgramID         pgtype.UUID
	ProgramName       string
}

func (q *Queries) GetTierByTierId(ctx context.Context, id pgtype.UUID) (GetTierByTierIdRow, error) {
	row := q.db.QueryRow(ctx, getTierByTierId, id)
	var i GetTierByTierIdRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Benefits,
		&i.Limitations,
		&i.Slug,
		&i.StripeProductID,
		&i.ExpirationType,
		&i.StripePriceID,
		&i.PriceInCents,
		&i.IsStudentRequired,
		&i.ProgramID,
		&i.ProgramName,
	)
	return i, err
}

const getTransactionByCheckoutSessionIdForUpdate = `-- name: GetTransactionByCheckoutSessionIdForUpdate :one
SELECT
    t.id,
    t.user_id,
    t.membership_id,
    t.tier_id,
    t.status,
    t.purchase_type,
    t.stripe_checkout_session_id,
    mt.program_id,
    mt.expiration_type
FROM transactions AS t
JOIN membership_tiers AS mt
    ON mt.id = t.tier_id
WHERE t.stripe_checkout_session_id = $1
FOR UPDATE OF t
`

type GetTransactionByCheckoutSessionIdForUpdateRow struct {
	ID                      pgtype.UUID
	UserID                  pgtype.UUID
	MembershipID            pgtype.UUID
	TierID                  pgtype.UUID
	Status                  TransactionStatusType
	PurchaseType            NullPurchaseType
	StripeCheckoutSessionID pgtype.Text
	ProgramID               pgtype.UUID
	ExpirationType          MembershipExpirationType
}

func (q *Queries) GetTransactionByCheckoutSessionIdForUpdate(ctx context.Context, stripeCheckoutSessionID pgtype.Text) (GetTransactionByCheckoutSessionIdForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByCheckoutSessionIdForUpdate, stripeCheckoutSessionID)
	var i GetTransactionByCheckoutSessionIdForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MembershipID,
		&i.TierID,
		&i.Status,
		&i.PurchaseType,
		&i.StripeCheckoutSessionID,
		&i.ProgramID,
		&i.ExpirationType,
	)
	return i, err
}

const getTransactionByTransactionIdForUpdate = `-- name: GetTransactionByTransactionIdForUpdate :one
SELECT
    t.id,
    t.user_id,
    t.membership_id,
    t.tier_id,
    t.status,
    t.purchase_type,
    t.stripe_checkout_session_id,
    mt.program_id,
    mt.expiration_type
FROM transactions AS t
JOIN membership_tiers AS mt
    ON mt.id = t.tier_id
WHERE t.id = $1
FOR UPDATE OF t
`

type GetTransactionByTransactionIdForUpdateRow struct {
	ID                      pgtype.UUID
	UserID                  pgtype.UUID
	MembershipID            pgtype.UUID
	TierID                  pgtype.UUID
	Status                  TransactionStatusType
	PurchaseType            NullPurchaseType
	StripeCheckoutSessionID pgtype.Text
	ProgramID               pgtype.UUID
	ExpirationType          MembershipExpirationType
}

func (q *Queries) GetTransactionByTransactionIdForUpdate(ctx context.Context, id pgtype.UUID) (GetTransactionByTransactionIdForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByTransactionIdForUpdate, id)
	var i GetTransactionByTransactionIdForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MembershipID,
		&i.TierID,
		&i.Status,
		&i.PurchaseType,
		&i.StripeCheckoutSessionID,
		&i.ProgramID,
		&i.ExpirationType,
	)
	return i, err
}

const putStripeCheckoutSessionId = `-- name: PutStripeCheckoutSessionId :execrows
UPDATE transactions
SET
    stripe_checkout_session_id = $2,
    updated_at = NOW()
WHERE id = $1
  AND status = 'pending'
`

type PutStripeCheckoutSessionIdParams struct {
	ID                      pgtype.UUID
	StripeCheckoutSessionID pgtype.Text
}

func (q *Queries) PutStripeCheckoutSessionId(ctx context.Context, arg PutStripeCheckoutSessionIdParams) (int64, error) {
	result, err := q.db.Exec(ctx, putStripeCheckoutSessionId, arg.ID, arg.StripeCheckoutSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePendingTransactionStatusByCheckoutId = `-- name: UpdatePendingTransactionStatusByCheckoutId :exec
UPDATE transactions
SET
    status = $2,
    updated_at = NOW()
WHERE stripe_checkout_session_id = $1 AND status = 'pending'
`

type UpdatePendingTransactionStatusByCheckoutIdParams struct {
	StripeCheckoutSessionID pgtype.Text
	Status                  TransactionStatusType
}

func (q *Queries) UpdatePendingTransactionStatusByCheckoutId(ctx context.Context, arg UpdatePendingTransactionStatusByCheckoutIdParams) error {
	_, err := q.db.Exec(ctx, updatePendingTransactionStatusByCheckoutId, arg.StripeCheckoutSessionID, arg.Status)
	return err
}

const updateTransactionStatusById = `-- name: UpdateTransactionStatusById :exec
UPDATE transactions
SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateTransactionStatusByIdParams struct {
	ID     pgtype.UUID
	Status TransactionStatusType
}

func (q *Queries) UpdateTransactionStatusById(ctx context.Context, arg UpdateTransactionStatusByIdParams) error {
	_, err := q.db.Exec(ctx, updateTransactionStatusById, arg.ID, arg.Status)
	return err
}
