// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AdminAuditOutcomeType string

const (
	AdminAuditOutcomeTypeSuccess AdminAuditOutcomeType = "success"
	AdminAuditOutcomeTypeFailed  AdminAuditOutcomeType = "failed"
	AdminAuditOutcomeTypeDenied  AdminAuditOutcomeType = "denied"
)

func (e *AdminAuditOutcomeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdminAuditOutcomeType(s)
	case string:
		*e = AdminAuditOutcomeType(s)
	default:
		return fmt.Errorf("unsupported scan type for AdminAuditOutcomeType: %T", src)
	}
	return nil
}

type NullAdminAuditOutcomeType struct {
	AdminAuditOutcomeType AdminAuditOutcomeType
	Valid                 bool // Valid is true if AdminAuditOutcomeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdminAuditOutcomeType) Scan(value interface{}) error {
	if value == nil {
		ns.AdminAuditOutcomeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdminAuditOutcomeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdminAuditOutcomeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdminAuditOutcomeType), nil
}

type ExecDisplayGroupType string

const (
	ExecDisplayGroupTypePresident       ExecDisplayGroupType = "president"
	ExecDisplayGroupTypeBoard           ExecDisplayGroupType = "board"
	ExecDisplayGroupTypeCentralDirector ExecDisplayGroupType = "central_director"
	ExecDisplayGroupTypeGameDirector    ExecDisplayGroupType = "game_director"
	ExecDisplayGroupTypeExecutive       ExecDisplayGroupType = "executive"
)

func (e *ExecDisplayGroupType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExecDisplayGroupType(s)
	case string:
		*e = ExecDisplayGroupType(s)
	default:
		return fmt.Errorf("unsupported scan type for ExecDisplayGroupType: %T", src)
	}
	return nil
}

type NullExecDisplayGroupType struct {
	ExecDisplayGroupType ExecDisplayGroupType
	Valid                bool // Valid is true if ExecDisplayGroupType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExecDisplayGroupType) Scan(value interface{}) error {
	if value == nil {
		ns.ExecDisplayGroupType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExecDisplayGroupType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExecDisplayGroupType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExecDisplayGroupType), nil
}

type ExecSocialPlatformType string

const (
	ExecSocialPlatformTypeInstagram ExecSocialPlatformType = "instagram"
	ExecSocialPlatformTypeX         ExecSocialPlatformType = "x"
	ExecSocialPlatformTypeTwitch    ExecSocialPlatformType = "twitch"
	ExecSocialPlatformTypeYoutube   ExecSocialPlatformType = "youtube"
	ExecSocialPlatformTypeTiktok    ExecSocialPlatformType = "tiktok"
	ExecSocialPlatformTypeLinkedin  ExecSocialPlatformType = "linkedin"
)

func (e *ExecSocialPlatformType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExecSocialPlatformType(s)
	case string:
		*e = ExecSocialPlatformType(s)
	default:
		return fmt.Errorf("unsupported scan type for ExecSocialPlatformType: %T", src)
	}
	return nil
}

type NullExecSocialPlatformType struct {
	ExecSocialPlatformType ExecSocialPlatformType
	Valid                  bool // Valid is true if ExecSocialPlatformType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExecSocialPlatformType) Scan(value interface{}) error {
	if value == nil {
		ns.ExecSocialPlatformType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExecSocialPlatformType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExecSocialPlatformType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExecSocialPlatformType), nil
}

type GroupType string

const (
	GroupTypeMember          GroupType = "member"
	GroupTypeCompetitiveTeam GroupType = "competitive_team"
	GroupTypeExecutive       GroupType = "executive"
	GroupTypeDirector        GroupType = "director"
	GroupTypeBoard           GroupType = "board"
)

func (e *GroupType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GroupType(s)
	case string:
		*e = GroupType(s)
	default:
		return fmt.Errorf("unsupported scan type for GroupType: %T", src)
	}
	return nil
}

type NullGroupType struct {
	GroupType GroupType
	Valid     bool // Valid is true if GroupType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGroupType) Scan(value interface{}) error {
	if value == nil {
		ns.GroupType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GroupType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGroupType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GroupType), nil
}

type MembershipExpirationType string

const (
	MembershipExpirationTypeSemester MembershipExpirationType = "semester"
	MembershipExpirationTypeYear     MembershipExpirationType = "year"
	MembershipExpirationTypeDay      MembershipExpirationType = "day"
)

func (e *MembershipExpirationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipExpirationType(s)
	case string:
		*e = MembershipExpirationType(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipExpirationType: %T", src)
	}
	return nil
}

type NullMembershipExpirationType struct {
	MembershipExpirationType MembershipExpirationType
	Valid                    bool // Valid is true if MembershipExpirationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipExpirationType) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipExpirationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipExpirationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipExpirationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipExpirationType), nil
}

type PaymentMethodType string

const (
	PaymentMethodTypeStripe    PaymentMethodType = "stripe"
	PaymentMethodTypeCash      PaymentMethodType = "cash"
	PaymentMethodTypeEtransfer PaymentMethodType = "etransfer"
)

func (e *PaymentMethodType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethodType(s)
	case string:
		*e = PaymentMethodType(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethodType: %T", src)
	}
	return nil
}

type NullPaymentMethodType struct {
	PaymentMethodType PaymentMethodType
	Valid             bool // Valid is true if PaymentMethodType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethodType) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethodType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethodType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethodType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethodType), nil
}

type PurchaseType string

const (
	PurchaseTypeNew     PurchaseType = "new"
	PurchaseTypeUpgrade PurchaseType = "upgrade"
)

func (e *PurchaseType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PurchaseType(s)
	case string:
		*e = PurchaseType(s)
	default:
		return fmt.Errorf("unsupported scan type for PurchaseType: %T", src)
	}
	return nil
}

type NullPurchaseType struct {
	PurchaseType PurchaseType
	Valid        bool // Valid is true if PurchaseType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPurchaseType) Scan(value interface{}) error {
	if value == nil {
		ns.PurchaseType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PurchaseType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPurchaseType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PurchaseType), nil
}

type RoleType string

const (
	RoleTypeMember RoleType = "member"
	RoleTypeAdmin  RoleType = "admin"
)

func (e *RoleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleType(s)
	case string:
		*e = RoleType(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleType: %T", src)
	}
	return nil
}

type NullRoleType struct {
	RoleType RoleType
	Valid    bool // Valid is true if RoleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleType) Scan(value interface{}) error {
	if value == nil {
		ns.RoleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleType), nil
}

type TransactionStatusType string

const (
	TransactionStatusTypePending   TransactionStatusType = "pending"
	TransactionStatusTypeCompleted TransactionStatusType = "completed"
	TransactionStatusTypeFailed    TransactionStatusType = "failed"
	TransactionStatusTypeRefunded  TransactionStatusType = "refunded"
	TransactionStatusTypeExpired   TransactionStatusType = "expired"
)

func (e *TransactionStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionStatusType(s)
	case string:
		*e = TransactionStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionStatusType: %T", src)
	}
	return nil
}

type NullTransactionStatusType struct {
	TransactionStatusType TransactionStatusType
	Valid                 bool // Valid is true if TransactionStatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionStatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionStatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionStatusType), nil
}

type Account struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	Provider             string
	ProviderAccountID    pgtype.Text
	AccessToken          string
	RefreshToken         pgtype.Text
	AccessTokenExpiresAt pgtype.Timestamptz
	Scope                string
	IDToken              pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type AdminAuditLog struct {
	ID           pgtype.UUID
	OccurredAt   pgtype.Timestamptz
	ActorUserID  pgtype.UUID
	Action       string
	TargetUserID pgtype.UUID
	Outcome      AdminAuditOutcomeType
	RequestID    string
	Description  pgtype.Text
}

type ExecProfile struct {
	UserID       pgtype.UUID
	Title        string
	DisplayOrder int32
	DisplayGroup ExecDisplayGroupType
	UpdatedAt    pgtype.Timestamptz
}

type ExecSocialLink struct {
	UserID    pgtype.UUID
	Platform  ExecSocialPlatformType
	Url       string
	UpdatedAt pgtype.Timestamptz
}

type Membership struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	TierID      pgtype.UUID
	StartedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	CancelledAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type MembershipProgram struct {
	ID          pgtype.UUID
	ProgramName string
}

type MembershipTier struct {
	ID              pgtype.UUID
	Title           string
	Description     pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	StripeProductID pgtype.Text
	IsActive        bool
	Slug            pgtype.Text
	Group           NullGroupType
	Benefits        []string
	ProgramID       pgtype.UUID
	ExpirationType  MembershipExpirationType
}

type MembershipTierPrice struct {
	ID                pgtype.UUID
	TierID            pgtype.UUID
	StripePriceID     pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	IsStudentRequired pgtype.Bool
	PriceInCents      pgtype.Int8
}

type Session struct {
	ID         pgtype.UUID
	Token      string
	UserID     pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	LastAccess pgtype.Timestamptz
	Metadata   pgtype.Text
}

type Transaction struct {
	ID                      pgtype.UUID
	UserID                  pgtype.UUID
	MembershipID            pgtype.UUID
	StripePaymentIntentID   pgtype.Text
	Status                  TransactionStatusType
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	GroupAtPurchase         NullGroupType
	StudentAtPurchase       pgtype.Bool
	AmountPaidCents         pgtype.Int8
	PurchaseType            NullPurchaseType
	StripeCheckoutSessionID pgtype.Text
	TierID                  pgtype.UUID
	PaymentMethod           PaymentMethodType
}

type User struct {
	ID                    pgtype.UUID
	Email                 string
	StudentID             pgtype.Text
	Role                  RoleType
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	FullName              string
	EmailVerifiedAt       pgtype.Timestamptz
	Password              pgtype.Text
	IsStudent             bool
	OnboardingCompletedAt pgtype.Timestamptz
	AvatarUrl             pgtype.Text
}

type UserGroup struct {
	UserID     pgtype.UUID
	Group      GroupType
	AssignedAt pgtype.Timestamptz
}

type Verification struct {
	ID        pgtype.UUID
	Subject   string
	Value     string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
