// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureMemberGroupForUser = `-- name: EnsureMemberGroupForUser :exec
INSERT INTO user_groups (
    user_id,
    "group"
)
VALUES (
    $1,
    'member'
)
ON CONFLICT (user_id, "group") DO NOTHING
`

func (q *Queries) EnsureMemberGroupForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ensureMemberGroupForUser, userID)
	return err
}

const getProfileByUserID = `-- name: GetProfileByUserID :one
SELECT
    u.id,
    u.email,
    u.student_id,
    u.role,
    u.created_at,
    u.updated_at,
    u.full_name,
    u.email_verified_at,
    u.is_student,
    u.onboarding_completed_at,
    u.avatar_url,
    COALESCE(g.groups, '{}'::text[])::text[] AS groups
FROM users u
LEFT JOIN LATERAL (
    SELECT array_agg(ug."group"::text ORDER BY ug.assigned_at ASC, ug."group" ASC) AS groups
    FROM user_groups ug
    WHERE ug.user_id = u.id
) g ON true
WHERE u.id = $1
`

type GetProfileByUserIDRow struct {
	ID                    pgtype.UUID
	Email                 string
	StudentID             pgtype.Text
	Role                  RoleType
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	FullName              string
	EmailVerifiedAt       pgtype.Timestamptz
	IsStudent             bool
	OnboardingCompletedAt pgtype.Timestamptz
	AvatarUrl             pgtype.Text
	Groups                []string
}

func (q *Queries) GetProfileByUserID(ctx context.Context, id pgtype.UUID) (GetProfileByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getProfileByUserID, id)
	var i GetProfileByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.StudentID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FullName,
		&i.EmailVerifiedAt,
		&i.IsStudent,
		&i.OnboardingCompletedAt,
		&i.AvatarUrl,
		&i.Groups,
	)
	return i, err
}

const onboardUserByUserId = `-- name: OnboardUserByUserId :exec
WITH onboarded AS (
    UPDATE users
    SET
        is_student = $2,
        student_id = $3,
        full_name = $4,
        onboarding_completed_at = NOW(),
        updated_at = NOW()
    WHERE id = $5
      AND onboarding_completed_at IS NULL
    RETURNING id
), executive_group AS (
    INSERT INTO user_groups (user_id, "group")
    SELECT id, 'executive'::group_type
    FROM onboarded
    WHERE $1::boolean
    ON CONFLICT (user_id, "group") DO NOTHING
)
INSERT INTO exec_profile (user_id)
SELECT id
FROM onboarded
WHERE $1::boolean
ON CONFLICT (user_id) DO NOTHING
`

type OnboardUserByUserIdParams struct {
	IsExecutive bool
	IsStudent   bool
	StudentID   pgtype.Text
	FullName    string
	ID          pgtype.UUID
}

func (q *Queries) OnboardUserByUserId(ctx context.Context, arg OnboardUserByUserIdParams) error {
	_, err := q.db.Exec(ctx, onboardUserByUserId,
		arg.IsExecutive,
		arg.IsStudent,
		arg.StudentID,
		arg.FullName,
		arg.ID,
	)
	return err
}
